### ISSUE TITLE
老师，能提供下数据库sql脚本吗？

### ISSUE THREAD

**Issue by andy521** [chenxofhit/BioDashboard#2]

**Comment by chenxofhit** [comment]
你留下你的邮箱，我私发给你，或者加我 qq 723357969

**Comment by JuLian1130** [comment]
Julian1130@163.com，麻烦给下sql脚本多谢了

**Comment by JuLian1130** [comment]
> 你留下你的邮箱，我私发给你，或者加QQ群 690853899

Julian1130@163.com，麻烦给下sql脚本多谢了

**Comment by JuLian1130** [comment]
> 你留下你的邮箱，我私发给你，或者加QQ群 690853899

@chenxofhit   Julian1130@163.com，麻烦给下sql脚本多谢了

**Comment by chenxofhit** [comment]
@JuLian1130 麻烦直接加下qq群~
