### ISSUE TITLE
忘记密码问题的解决

### ISSUE THREAD

**Issue by zjsgit** [chenxofhit/BioDashboard#6]
希望能够通过注册的邮箱找回密码

**Comment by chenxofhit** [comment]
一般学生或者员工可以联系上级或者直接联系系统管理员来重置密码即可，由员工或者学生自行的重置密码目前不被支持，虽然这个功能很常见，但是很多浏览器都有记忆密码功能，没有刻意去做。

**Comment by chenxofhit** [comment]
如果没有其它问题，暂时关闭这个issue了，谢谢关注。
